# Enfòmasyon sou Sit la
title: Boutique Piyay
email: josephgenescar@gmail.com
description: >- 
  Byenvini nan Boutique Piyay, pi bon kote pou jwenn pwodwi ou bezwen.
baseurl: "" 
url: "https://rivayo3.netlify.app"

# Enfòmasyon sou Otè a
author:
  name: "Joseph Genescar"
  twitter: "josephgenescar"

# Konfigirasyon Build la
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Konfigirasyon Koleksyon yo (Sa pa dwe anndan 'exclude')
collections:
  posts:
    output: true
  projects:
    output: true
  products:
    output: true

# Ekskli fichye sa yo
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .netlify/

# Konfigirasyon Netlify CMS (Opsyonèl pou Jekyll)
netlify_cms:
  admin_config_path: "admin/config.yml"