# Enfòmasyon sou Sit la
title: Boutique Piyay
email: josephgenescar@gmail.com
description: >- 
  Byenvini nan Boutique Piyay, pi bon kote pou jwenn pwodwi ou bezwen.
baseurl: "" 
url: "https://boutique-piyay.netlify.app"

# Enfòmasyon sou Otè a
author:
  name: "Joseph Genescar"
  twitter: "josephgenescar"

# Konfigirasyon Build la
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Konfigirasyon Koleksyon yo
collections:
  products:
    output: true
    permalink: /pwodwi/:path/
  categories:
    output: true
    permalink: /kategori/:path/

# Defaults pou koleksyon yo
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Ekskli fichye sa yo
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .netlify/

# Konfigirasyon Netlify CMS
netlify_cms:
  admin_config_path: "admin/config.yml"
  admin_index_path: "admin/index.html"
  public_folder: "assets/images/uploads"
  media_folder: "assets/images/uploads"